version: '3.5'
networks:
  proxynet:
    external: true
services:
  wordpress:
    depends_on:
      - yeicopgamer_db
    image: wordpress:latest
    container_name : yeicopgamer
    volumes:
     - ./html:/var/www/html
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    expose:
      - 80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=yeicopgamer.com,www.yeicopgamer.com
      - LETSENCRYPT_HOST=yeicopgamer.com,www.yeicopgamer.com
      - LETSENCRYPT_EMAIL=luise.ruelasz@gmail.com
      - WORDPRESS_DB_HOST:db
      - WORDPRESS_DB_USER:luis
      - WORDPRESS_DB_PASSWORD:123456789
      - WORDPRESS_DB_NAME:appyeicopgamer
    networks:
      - proxynet

  yeicopgamer_db:
    container_name: yeicopgamer_db
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    ports:
      - 3346:3306
    environment:
      - MYSQL_ROOT_PASSWORD:123456789
      - MYSQL_DATABASE:appyeicopgamer
      - MYSQL_USER:luis
      - MYSQL_PASSWORD:123456789
    networks:
      - proxynet
